/*
* BANK ACCOUNT CHALLENGE
*
* CREATE A NEW CLASS FOR BANK ACCOUNT
* CREATE FIELDS FOR THE ACCOUNT NUMBER, BALANCE, CUSTOMER NAME, EMAIL, AND PHONE NUMBER
*
* CREATE GETTERS AND SETTERS FOR EACH FIELD
* CREATE TWO ADDITIONAL METHODS
* 1. TO ALLOW THE CUSTOMER TO DEPOSIT FUNDS (THIS SHOULD INCREMENT THE BALANCE FIELD)
* 2. TO ALLOW THE CUSTOMER TO WITHDRAW FUNDS (THIS SHOULD DEDUCT FROM THE BALANCE FIELD,
*   BUT NOT ALLOW THE WITHDRAWAL TO COMPLETE IF THE'YRE ARE INSUFFICIENT FUNDS)
* */

public class Main {
    public static void main(String[] args) {
        Account account1 = new Account();
        account1.withdraw((100.0));

    }
}
